### ISSUE TITLE
[Plugin] 设计插件数据规范

### ISSUE THREAD

**Issue by qhfir** [FlowCI/flow-platform#150]

**Comment by yunheli** [comment]
# Plugin 数据格式定义

### flowci/plugins
- repository
- README

### 开发者贡献插件
- 把插件的信息 与 主项目 flowci/plugin_repos pr 添加json

	```
	{
		name: "fircli",
		url: "http://github.com/fircli",
		author: "fir",
		platform: ["*", windows, mac , linux],
		language: 
		labels: ["fir", "uploader", "fir.im"]
	}
	```

- 如果 merge 了 自动 Fork 一份到 flowci/fircli
- 每次打tag 后台每隔一小时去拉取一下最新的项目信息，如果有更新就更新market信息，同时把tag 自动加到 flowci/fircli


### Market 的 信息
- name
- title
- readme P
- git url
- issue url
- author
- labels
- platform
- stars


public abstract class FlowPlugin {
	
}

{
	inputs: {
		FLOW_1: {
			type: int,
			required: true
			values: ["1", "2", "3"]
		},

		FLOW_2: {
		xxxx
		}
	}
}

PluginContext {
	inputs;
	outputs;
}

public abstract class PluginRunner {
	
	void onStart(PluginContext context) {
		context.outputs.add(FLOW_1, test);
	}
}


public class PluginMain {
	
	xxxx
}



INPUTS=A ./run.sh


java -jar xx.jar $INPUTS
