### ISSUE TITLE
建议增加上传至fir功能

### ISSUE THREAD

**Issue by XTShow** [FlowCI/flow-platform#184]
建议增加构建完成后，自动上传至fir的功能，方便使用二维码进行.ipa的分发，谢谢！

**Comment by qhfir** [comment]
上传 fir 功能我们会在下个版本上线，敬请期待。

**Comment by qhfir** [comment]
## fir 上传脚本（此脚本只能用于发布应用）：

- 首先在终端运行以下命令安装 fir.sh：

`curl https://raw.githubusercontent.com/FIRHQ/fir-cli/master/fir.sh -o /usr/local/bin/fir
chmod +x /usr/local/bin/fir`

- 登录 fir 账户， 获取 token，启动 docker 并在终端执行以下命令（第一次会自动下载 fir-cli 镜像）：

`fir login token`

在 flowci yml 工作流最后添加 fir 发布脚本，如下：

`- name: fir_publish
        script: |
          cd ${IOS_PROJECT_NAME}
          array=$(find ${IOS_IPA_DIR} -name *.ipa 2>&1)
          for file in ${array[@]}
          do
            fir publish $file
          done`

发布效果：

![1](https://user-images.githubusercontent.com/28887077/33196774-653e6ef8-d11c-11e7-8f02-ef1d6b743218.jpg)

**Comment by XTShow** [comment]
亲测可用！👍

**Comment by lizhaofastlaneci** [comment]
log上提示fastlane 命令找不到，但是本地是可以的，如何解决
