### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by WiHi** [FlowCI/flow-platform#217]
1.使用docker安装flowci/mysql启动失败，报/var/lib/mysql目录找不到，注释docker-compose.yml中如下部分启动成功：
    volumes:
      - "~/flow-ci/db:/var/lib/mysql"
2.关于两个domain设置的问题，设置默认两个都为主机IP，登录时浏览器控制台出现跨域问题，请问该如何设置
FLOW_API_DOMAIN: 
FLOW_WEB_DOMAIN:

**Comment by yang-guo-2016** [comment]
@WiHi 可以提供一下失败的日志 和 控制台的截图嘛 ？

**Comment by WiHi** [comment]
今天早晨重新尝试安装一遍可以正常运行了，估计昨天运行的容器未正常关闭导致端口冲突，然后导致mysql没有正常启动，总之最初没有安装docker安装的标准方法执行，谢谢回复

**Comment by yang-guo-2016** [comment]
好的好的，有什么问题随时沟通~
