### ISSUE TITLE
Unable to create agent via control center

### ISSUE THREAD

**Issue by weweliang** [FlowCI/flow-platform#220]
docker方式安装的。启动好登陆到控制台后，准备创建agent获取token，但控制台根本创建不了

**Comment by qhfir** [comment]
创建不了指的是？ 点击无反应？有报错吗

**Comment by yunheli** [comment]
@stargwq 你是怎么起的？方便把命令发一下么？

**Comment by yunheli** [comment]
@weweliang 你是怎么起的？方便把命令发一下么？

**Comment by weweliang** [comment]
FLOW_API_DOMAIN=yourhost.com FLOW_WEB_DOMAIN=yourhost.com ./start-services.sh 这样启动，域名换成IP。

![image](https://user-images.githubusercontent.com/667271/33654305-a96476bc-daaa-11e7-848f-fdd28e71eb40.png)

**Comment by yunheli** [comment]
@weweliang 方便留个联系方式么？ 或者加QQ:1059103388

**Comment by yunheli** [comment]
@weweliang ?

**Comment by hihunk** [comment]
看起来，修改了后台API的端口号后，会出这个问题，改回默认的8080后，就可以了
