### ISSUE TITLE
webhook 没响应是怎么回事

### ISSUE THREAD

**Issue by MiYogurt** [FlowCI/flow-platform#225]
coding 和 github 的我都试过了。

我还特地做了内网穿透，浏览器可以访问，配置到服务就不行。

```
$ http post http://mymac.nodelover.me:8080/flow-api/hooks/git/nodejs_test
HTTP/1.1 200
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, X-Authorization, Authenticate, Library
Access-Control-Allow-Methods: GET, POST, PATCH, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3600
Content-Length: 0
Date: Thu, 07 Dec 2017 02:44:20 GMT
```

![image](https://user-images.githubusercontent.com/10082395/33696283-7f73bea2-db3c-11e7-85f3-d6cbc30501ea.png)

![image](https://user-images.githubusercontent.com/10082395/33696297-92214cc2-db3c-11e7-9f4e-01435d99fdc2.png)

是不是因为这个的问题，这个我是在本地起的，不在 docker 里面。

折腾了一上午都没跑起来一个 nodejs demo，太难用了。

**Comment by yunheli** [comment]
@MiYogurt 加群 154788427 ， 我来给你解决问题
