### ISSUE TITLE
docker启动的时候mysql数据库启动失败

### ISSUE THREAD

**Issue by ourstorys** [FlowCI/flow-platform#248]
ls: cannot open directory '/var/lib/mysql': Permission denied
chown: changing ownership of '/var/lib/mysql': Permission denied
Cannot change ownership of the database directories to the 'mysql'
user.  Check that you have the necessary permissions and try again.
[FAIL] Starting MariaDB database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!

请帮忙看下什么原因？

**Comment by yunheli** [comment]
@ourstorys 您好，~/flow-ci/db 文件夹存在么？

**Comment by yunheli** [comment]
看日志是由于 ~/flow-ci/db文件夹没挂载进去才导致没权限访问， 请问你的机器是什么？ windows mac or linux?

**Comment by yunheli** [comment]
@ourstorys

**Comment by ourstorys** [comment]
是linux-centos7，在docker-compose中是有这个路径挂载的

**Comment by yunheli** [comment]
@ourstorys 你机器中有这个路径么？  ~/flow-ci/db, 或者看看 机器上这个目录的权限

**Comment by yunheli** [comment]
现在docker里面没权限访问这个目录

**Comment by yunheli** [comment]
方便留联系方式么？或者+Q:1059103388

**Comment by ourstorys** [comment]
在docker-compose中加入 privileged：true 就可以了。有没有QQ交流的群：496725775。谢谢

**Comment by yunheli** [comment]
@ourstorys  FlowCI群 154788427
