### ISSUE TITLE
[Agent] Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by Arc-lin** [FlowCI/flow-platform#302]
linghitdeMac-mini:docker-master linghit$ java -jar agent/flow-agent-v0.1.4-alpha.jar http://frp.arclin.me:8080/flow-api 53abded7-ac38-4ea3-b6eb-7775ba13abbd
2018-03-26 18:05:08.321 [TRACE] App - ========= Flow Agent Started =========
2018-03-26 18:05:08.323 [TRACE] App - === Server: http://frp.arclin.me:8080/flow-api
2018-03-26 18:05:08.324 [TRACE] App - === Token:  53abded7-ac38-4ea3-b6eb-7775ba13abbd
2018-03-26 18:05:08.324 [TRACE] App - === Start to load configuration
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2018-03-26 18:05:09.223 [TRACE] App - ====== Settings: AgentSettings{agentPath=default#iOS, webSocketUrl='ws://frp.arclin.me:8080/flow-api/agent/cmd/logging', cmdStatusUrl='http://frp.arclin.me:8080/flow-control-center/cmd/report', cmdLogUrl='http://frp.arclin.me:8080/flow-control-center/cmd/log/upload', zookeeperUrl='frp.arclin.me:2181'} com.flow.platform.domain.AgentSettings@45b4c3a9
2018-03-26 18:05:09.223 [TRACE] App - ====== Zookeeper host: frp.arclin.me:2181
2018-03-26 18:05:09.223 [TRACE] App - ====== Working zone: default
2018-03-26 18:05:09.224 [TRACE] App - ====== Agent agent: iOS
2018-03-26 18:05:09.224 [TRACE] App - ========= Config initialized =========
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2018-03-26 18:05:10.197 [TRACE] AgentManager:ZK-Event - ========= Node Added: /flow-agents/default/iOS =========
2018-03-26 18:05:10.197 [TRACE] AgentManager:ZK-Event - ========= Initialized =========

Agent count not start as usual. What should I do?

**Comment by yunheli** [comment]
@Arc-lin 启动成功了啊，看日志

**Comment by Arc-lin** [comment]
现在是出现 了
[https://i.loli.net/2018/03/26/5ab8c81ca2734.png](url)
这样子的情况 

启动过程中  中间有一行
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

我猜会不会是这个原因导致的

**Comment by yunheli** [comment]
@Arc-lin 这个不影响

**Comment by yunheli** [comment]
@Arc-lin 看日志已经启动了

**Comment by yunheli** [comment]
@Arc-lin 我能访问你的admin页面么

**Comment by Arc-lin** [comment]
可以, 本来就是测试用的
frp.arclin.me:8001
账号admin  密码123456

**Comment by yunheli** [comment]
ok , 我创建个Agent试试

**Comment by yunheli** [comment]
@Arc-lin 能看到 api的日志么 报什么错误么

**Comment by Arc-lin** [comment]
flow.ci_1   | 26-Mar-2018 10:20:17.129 INFO [MessageBroker-1] org.apache.coyote.AbstractProcessor.setErrorState An error occurred in processing while on a non-container thread. The connection will be closed immediately
flow.ci_1   |  java.io.IOException: Broken pipe
flow.ci_1   | 	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
flow.ci_1   | 	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
flow.ci_1   | 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
flow.ci_1   | 	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
flow.ci_1   | 	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
flow.ci_1   | 	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
flow.ci_1   | 	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
flow.ci_1   | 	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
flow.ci_1   | 	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1259)
flow.ci_1   | 	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:670)
flow.ci_1   | 	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:607)
flow.ci_1   | 	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:597)
flow.ci_1   | 	at org.apache.coyote.http11.Http11OutputBuffer.flushBuffer(Http11OutputBuffer.java:581)
flow.ci_1   | 	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:272)
flow.ci_1   | 	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1511)
flow.ci_1   | 	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:282)
flow.ci_1   | 	at org.apache.coyote.Response.action(Response.java:173)
flow.ci_1   | 	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:317)
flow.ci_1   | 	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:284)
flow.ci_1   | 	at org.apache.catalina.connector.Response.flushBuffer(Response.java:541)
flow.ci_1   | 	at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:312)
flow.ci_1   | 	at org.springframework.http.server.ServletServerHttpResponse.flush(ServletServerHttpResponse.java:96)
flow.ci_1   | 	at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.writeFrameInternal(AbstractHttpSockJsSession.java:350)
flow.ci_1   | 	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:318)
flow.ci_1   | 	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendHeartbeat(AbstractSockJsSession.java:251)
flow.ci_1   | 	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession$HeartbeatTask.run(AbstractSockJsSession.java:453)
flow.ci_1   | 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
flow.ci_1   | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
flow.ci_1   | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
flow.ci_1   | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
flow.ci_1   | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
flow.ci_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
flow.ci_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
flow.ci_1   | 	at java.lang.Thread.run(Thread.java:748)
flow.ci_1   |

**Comment by Arc-lin** [comment]
还有一个
`
 2018-03-26 10:18:27.383 [ERROR] GlobalExceptionHandler - 
flow.ci_1   | java.lang.ClassCastException: org.eclipse.jgit.transport.TransportHttp cannot be cast to org.eclipse.jgit.transport.SshTransport
flow.ci_1   | 	at com.flow.platform.util.git.GitSshClient.lambda$initSessionFactory$0(GitSshClient.java:83)
flow.ci_1   | 	at org.eclipse.jgit.api.TransportCommand.configure(TransportCommand.java:139)
`

**Comment by yunheli** [comment]
+Q:1059103388

**Comment by Arc-lin** [comment]
好的  晚点联系您

**Comment by yunheli** [comment]
好的

**Comment by Arc-lin** [comment]
你好 , 我今天早上重新配置了一遍之后又可以了, 可能是我之前哪个步骤错了, 谢谢了哈
