### ISSUE TITLE
git clone 代码失败

### ISSUE THREAD

**Issue by sdaduanbilei** [FlowCI/flow-platform#306]
```
正克隆到 'jiuji2'...
Warning: Permanently added 'gitee.com,116.211.167.14' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。
```

ssh 方式，并且在 创建flow 的时候，已经test 是通过的，能正常获取到分支信息。
还有 http 方式一直test 不成功
```
Fail to pull with specific files: Read timed out after 30,000 ms
```

在线等

**Comment by yunheli** [comment]
@sdaduanbilei agent 机器有访问 git 的权限么？

**Comment by yang-guo-2016** [comment]
因为实际执行任务的是 Agent，错误应该是 Agent 上没有权限克隆代码，需要把 Agent 上的 SSH Key 加入到 gitee 仓库的 Deploy Key 里面

**Comment by sdaduanbilei** [comment]
@yunheli @yang-guo-2016  之前是有添加的，但是一直处于 正在构建  而且也没日志，转圈 ，重新添加了 还是一直！

**Comment by sdaduanbilei** [comment]
已经可以了正常编译，注意事项： 1 创建的时候 必须添加一个 ```credentials``` 否则无法链接成功，也无法获取到分支信息。2 agent 本机必须也设置ssh key  
问题：目前http 方式还未成功连接过
