### ISSUE TITLE
how to handle error

### ISSUE THREAD

**Issue by shaotianchi** [FlowCI/flow-platform#311]
Can I handle error when task failed
任务失败的时候是否有回调可以处理

**Comment by yunheli** [comment]
@shaotianchi  FAILURE 就表示 job失败了

**Comment by shaotianchi** [comment]
> FLOW_JOB_LAST_STATUS: 可以通过此环境变量获取上一步的构建结果 SUCCESS, FAILURE, STOPPED, TIMEOUT

根据这个描述如果 step1 失败 step2 成功 step3 能够判断 step1 失败吗

**Comment by shaotianchi** [comment]
奥 我理解了
