### ISSUE TITLE
flow 一直在准备中，无法开始

### ISSUE THREAD

**Issue by shaotianchi** [FlowCI/flow-platform#315]
![25bdb0dbec0fd5a51a994037614df21f](https://user-images.githubusercontent.com/2035693/40092916-755d0098-58f2-11e8-8197-050314d22975.jpg)
![0dbf9bed27bebd6eaeda11c4200008f7](https://user-images.githubusercontent.com/2035693/40092920-7a92914a-58f2-11e8-9780-b6c0dd53e633.jpg)
![0b8c20ce63899edc21e85ca2051860b9](https://user-images.githubusercontent.com/2035693/40092928-835a3e86-58f2-11e8-8754-31c2e1bf39a0.jpg)
![_30_master_ _sccbusinessrouter](https://user-images.githubusercontent.com/2035693/40092961-b2efe89e-58f2-11e8-9b6d-bdd286b560e1.png)
Agent 已经启动，但是flow 的信息里面都没有 agent 的设置

**Comment by yunheli** [comment]
@shaotianchi agent 配置有问题， Agent怎么启动的？

**Comment by yunheli** [comment]
@shaotianchi 把Agent启动的命令贴一下

**Comment by shaotianchi** [comment]
@yunheli 重启服务就好了 但是我今天重启以后接口就没法调用了 
![image](https://user-images.githubusercontent.com/2035693/40153135-d1cfb7d0-59ba-11e8-94e2-b27a6d4a7616.png)

**Comment by shaotianchi** [comment]
现在登录一直超时，服务端的 log 里也没有输出，根本不知道什么问题。

**Comment by shaotianchi** [comment]
![image](https://user-images.githubusercontent.com/2035693/40155039-1eadb4a4-59c4-11e8-9355-5c14fdf84952.png)

**Comment by shaotianchi** [comment]
@yunheli

**Comment by shaotianchi** [comment]
出这个问题的原因应该是我昨天把 docker 卸载重装了一遍，之后启动以后就一直这样了

**Comment by shaotianchi** [comment]
删除 /home/xx/data/flowci/mysql 之后重新启动就可以了
