### ISSUE TITLE
构建时页面无响应

### ISSUE THREAD

**Issue by EvoIos** [FlowCI/flow-platform#316]
macOS 系统，fastlane 构建 iOS 项目，查看日志的时候，因为 fastlane build 输出太多日志卡住了，导致页面无响应。

是否可以优化下？

http://localhost:3000/flows/test-Adhoc/jobs/31/logs

![snip20180525_1](https://user-images.githubusercontent.com/12396910/40522264-9e14a24a-6002-11e8-9353-579590146720.png)

**Comment by yunheli** [comment]
@EvoIos 谢谢反馈，之后会优化
